[package]
name = "double-zero-raiser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspaces]
members = [
    "crates/todos",
    "crates/utils",
    "crates/websocket"
]

[dependencies]
axum = "0.4"
futures = "0.3"
tokio = "1"
tower = { version = "0.4", features = ["util"] }
tracing = "0.1"
tracing-subscriber = { version="0.3", features = ["env-filter"] }