version: "3.8"
services:
  db:
    image: postgres:alpine
    container_name: alchem
    environment:
      - POSTGRES_USER=allen
      - POSTGRES_PASSWORD=zhang
      - POSTGRES_DB=alchem
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgres/data
    restart: always
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis/data
    restart: always
  # 后面要补上 flutter前端
  # application:
volumes:
  database_data:
    driver: local
  redis_data:
    driver: local
