version: "3.9"
services:
  db:
    image: postgres:alpine
    container_name: alchem
    environment:
      - POSTGRES_USER=allen
      - POSTGRES_PASSWORD=zhang
      - POSTGRES_DB=alchem
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgres/data
    restart: always
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis/data
    restart: always
  # pulsar:
  #   image: apachepulsar/pulsar
  #   container_name: pulsar
  #   ports:
  #     - 8080:8080
  #     - 6650:6650
  #   environment:
  #     PULSAR_MEM: " -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
  #     DB_URL: db:5432
  #   command: bin/pulsar standalone
  #   restart: always
  # 后面要补上 flutter前端
  # application:
volumes:
  database_data:
    driver: local
  redis_data:
    driver: local
