[package]
name = "alchem-websocket"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

alchem-utils = { version = "0.1.0",path = "../utils"}

axum = { version = "0.5", features = ["ws", "headers"] }
futures = "0.3"
redis = {version = "0.21", features = ["cluster","tokio-comp"]}
tokio = { version = "1", features = ["full"] }
tower = { version = "0.4", features = ["util"] }
tracing = "0.1"
tracing-subscriber = { version="0.3", features = ["env-filter"] }